# This file is automatically @generated by Poetry 1.5.4 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.0"
python-versions = ">=3.10.0,<3.12"
content-hash = "c72ba1872668238cc9b2c02a1118c7b8f9049473b63bbad4ee2bd46365be7ce2"
