#!/usr/bin/with-contenv bash

if [[ ! -f /usr/bin/apt ]]; then
cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *   universal-calibre mod is only supported on images  *
    *             using an Ubuntu base image.              *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
exit 0
fi

export DEBIAN_FRONTEND="noninteractive"

if [[ "$(calibredb --version)" != "calibredb (calibre 7.16)" ]]; then
    echo "[universal-calibre-setup] Installing Calibre version $(cat /CALIBRE_RELEASE)..."
    /app/calibre/calibre_postinstall
    if [[ $? == 0 ]]
    then
        echo "[universal-calibre-setup] Setup successful! Exiting now..." 
    else
        echo "[universal-calibre-setup] Setup unsuccessful, 'calibre_postinstall' encountered an error. Exiting now..." 
    fi
else
    echo "[universal-calibre-setup] Skipping setup, Calibre already installed. Exiting now..."
fi