#!/bin/bash

python3 /app/calibre-web-automated/scripts/auto-library.py

if [[ $? == 1 ]]
then
    echo "[cwa-auto-library] Service did not complete successfully (see errors above). Ending service..."
elif [[ $? == 0 ]]
then
    echo "[cwa-auto-library] Service completed successfully! Ending service..."
fi