# -*- coding: utf-8 -*-
# Calibre-Web Automated – fork of Calibre-Web
# Copyright (C) 2018-2025 Calibre-Web contributors
# Copyright (C) 2024-2025 Calibre-Web Automated contributors
# SPDX-License-Identifier: GPL-3.0-or-later
# See CONTRIBUTORS for full list of authors.

import datetime
import json
from urllib.parse import unquote_plus

from flask import Blueprint, request, render_template, make_response, abort, Response, g, url_for
from flask_babel import get_locale
from flask_babel import gettext as _
from flask_babel import lazy_gettext as N_


from sqlalchemy.sql.expression import func, text, or_, and_, true, false
from sqlalchemy.exc import InvalidRequestError, OperationalError

from . import logger, config, db, calibre_db, ub, isoLanguages, constants, magic_shelf
from .usermanagement import requires_basic_auth_if_no_ano, auth
from .helper import get_download_link, get_book_cover
from .pagination import Pagination
from .web import render_read_books


opds = Blueprint('opds', __name__)

log = logger.create()


# Issue #160 follow-up: every OPDS feed served by this blueprint accepts a
# ``?lang=xx`` query param (see ``cw_babel.get_locale``). The locale resolver
# honors it per-request, but every link in the returned XML is generated by
# ``url_for`` and therefore loses the param — so the next click reverts to
# English/Accept-Language/user.locale. Hooking ``url_defaults`` propagates
# ``lang`` into every ``url_for`` call inside the OPDS blueprint so an OPDS
# client that follows links stays in the language the user asked for.
#
# Only applies when ``lang`` is present on the current request, so non-OPDS
# usage is unaffected and clients that never pass ``lang`` see byte-identical
# output to before.
@opds.url_defaults
def _opds_propagate_lang(endpoint, values):
    if 'lang' in values:
        return
    try:
        lang = request.args.get('lang')
    except RuntimeError:
        return
    if lang:
        values['lang'] = lang


def _opds_paged_url(offset):
    """Build a same-path URL for OPDS pagination links with the rest of the
    inbound query args preserved (most importantly ``?lang=``). ``offset``
    of ``None`` produces the offset-less ``rel=first`` form.

    Fork issue #160 follow-up: the prior template construction
    ``request.path + '?offset=N'`` dropped every other query arg, so an
    OPDS client paging through a Hungarian feed via ``?lang=hu`` flipped
    back to English on the next page.
    """
    from urllib.parse import urlencode

    args = []
    seen_offset = False
    for key in request.args:
        if key == 'offset':
            seen_offset = True
            continue
        for value in request.args.getlist(key):
            args.append((key, value))
    if offset is not None:
        args.append(('offset', str(offset)))
    base = request.script_root + request.path
    if not args:
        return base
    return base + '?' + urlencode(args)


def _opds_search_url_path():
    """Build the OpenSearch search-URL template (path form) with
    ``{searchTerms}`` in the right spot relative to any propagated
    query string (notably ``?lang=xx``). Issue #160 follow-up.
    """
    placeholder = '__OPDS_SEARCH_PLACEHOLDER__'
    built = url_for('opds.feed_cc_search', query=placeholder)
    return built.replace(placeholder, '{searchTerms}')


def _format_opds_rating(value):
    """Render a rating value (rating/2 from the Calibre ratings table) as
    the shortest readable decimal — fork issue #180.

    Calibre stores ``ratings.rating`` as an INTEGER 0..10 (half-star
    granularity). ``cps/opds.py:feed_ratingindex`` divides by 2 in SQL
    so the displayable value is 0..5 in 0.5 steps. SQLAlchemy on some
    configurations returns the divided column as a ``Decimal`` with
    trailing zeros (``Decimal('3.0000000000')``) rather than a clean
    float — bare ``"{}".format(value)`` then renders the noise as
    ``"3.0000000000 Stars"``. Coerce to ``float`` and use ``g``
    formatting so whole stars render as ``"3"`` and half stars as
    ``"3.5"``."""
    return "{:g}".format(float(value))


def _is_real_pubdate(pubdate):
    """Return True if the pubdate looks like a real publication date
    rather than Calibre's ``DEFAULT_PUBDATE`` sentinel (or NULL) —
    fork issue #181.

    Calibre's metadata.db stores ``datetime(101, 1, 1, 0, 0, 0)`` when
    no pubdate is set. The OPDS template previously emitted that as
    ``<published>0101-01-01T00:00:00+00:00</published>``, which OPDS
    clients (Readest in particular) display as "Invalid Date." OPDS
    spec marks ``<published>`` as optional; omitting it for the
    sentinel is the right behavior. Real historical pubdates (Don
    Quixote 1605, etc.) are well past year 101 and still emit."""
    if pubdate is None:
        return False
    return pubdate != db.Books.DEFAULT_PUBDATE


@opds.context_processor
def _opds_template_helpers():
    return {
        'opds_paged_url': _opds_paged_url,
        'opds_search_url_path': _opds_search_url_path,
        '_is_real_pubdate': _is_real_pubdate,
    }

OPDS_ROOT_ORDER_DEFAULT = [
    'books',
    'hot',
    'top_rated',
    'recent',
    'random',
    'read',
    'unread',
    'authors',
    'publishers',
    'categories',
    'series',
    'languages',
    'ratings',
    'formats',
    'shelves',
    'magic_shelves',
]

# Issue #121: title/description strings on every entry below are wrapped with
# `N_()` (lazy_gettext) so pybabel-extract picks them up into messages.pot. The
# pre-fix dict held bare Python literals — pybabel can't follow `_(variable)`
# at extract time, so newer keys (`books`, `recent`, `magic_shelves`) never
# made it into the catalog and rendered as English even on a Hungarian-locale
# UI while the older keys (`hot`, `read`) showed translated.
OPDS_ROOT_ENTRY_DEFS = {
    'books': {
        'endpoint': 'opds.feed_booksindex',
        'title': N_('Alphabetical Books'),
        'description': N_('Books sorted alphabetically'),
        'visible': lambda user, allow_anonymous: True,
    },
    'hot': {
        'endpoint': 'opds.feed_hot',
        'title': N_('Hot Books'),
        'description': N_('Popular publications from this catalog based on Downloads.'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_HOT),
    },
    'top_rated': {
        'endpoint': 'opds.feed_best_rated',
        'title': N_('Top Rated Books'),
        'description': N_('Popular publications from this catalog based on Rating.'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_BEST_RATED),
    },
    'recent': {
        'endpoint': 'opds.feed_new',
        'title': N_('Recently added Books'),
        'description': N_('The latest Books'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_RECENT),
    },
    'random': {
        'endpoint': 'opds.feed_discover',
        'title': N_('Random Books'),
        'description': N_('Show Random Books'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_RANDOM),
    },
    'read': {
        'endpoint': 'opds.feed_read_books',
        'title': N_('Read Books'),
        'description': N_('Read Books'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_READ_AND_UNREAD) and not user.is_anonymous,
    },
    'unread': {
        'endpoint': 'opds.feed_unread_books',
        'title': N_('Unread Books'),
        'description': N_('Unread Books'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_READ_AND_UNREAD) and not user.is_anonymous,
    },
    'authors': {
        'endpoint': 'opds.feed_authorindex',
        'title': N_('Authors'),
        'description': N_('Books ordered by Author'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_AUTHOR),
    },
    'publishers': {
        'endpoint': 'opds.feed_publisherindex',
        'title': N_('Publishers'),
        'description': N_('Books ordered by publisher'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_PUBLISHER),
    },
    'categories': {
        'endpoint': 'opds.feed_categoryindex',
        'title': N_('Categories'),
        'description': N_('Books ordered by category'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_CATEGORY),
    },
    'series': {
        'endpoint': 'opds.feed_seriesindex',
        'title': N_('Series'),
        'description': N_('Books ordered by series'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_SERIES),
    },
    'languages': {
        'endpoint': 'opds.feed_languagesindex',
        'title': N_('Languages'),
        'description': N_('Books ordered by Languages'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_LANGUAGE),
    },
    'ratings': {
        'endpoint': 'opds.feed_ratingindex',
        'title': N_('Ratings'),
        'description': N_('Books ordered by Rating'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_RATING),
    },
    'formats': {
        'endpoint': 'opds.feed_formatindex',
        'title': N_('File formats'),
        'description': N_('Books ordered by file formats'),
        'visible': lambda user, __: user.check_visibility(constants.SIDEBAR_FORMAT),
    },
    'shelves': {
        'endpoint': 'opds.feed_shelfindex',
        'title': N_('Shelves'),
        'description': N_('Books organized in shelves'),
        'visible': lambda user, allow_anonymous: user.is_authenticated or allow_anonymous,
    },
    'magic_shelves': {
        'endpoint': 'opds.feed_magic_shelfindex',
        'title': N_('Magic Shelves'),
        'description': N_('Books organized in magic shelves'),
        'visible': lambda user, allow_anonymous: user.is_authenticated or allow_anonymous,
    },
}


def normalize_opds_root_order(order):
    if not isinstance(order, list):
        order = []
    seen = set()
    normalized = []
    for key in order:
        if key in OPDS_ROOT_ENTRY_DEFS and key not in seen:
            normalized.append(key)
            seen.add(key)
    for key in OPDS_ROOT_ORDER_DEFAULT:
        if key not in seen:
            normalized.append(key)
            seen.add(key)
    return normalized


def get_opds_root_order_for_user(user):
    try:
        order = (user.view_settings or {}).get('opds', {}).get('root_order', [])
    except Exception:
        order = []
    if not order:
        return OPDS_ROOT_ORDER_DEFAULT
    return normalize_opds_root_order(order)


def get_opds_hidden_entries_for_user(user):
    try:
        hidden = (user.view_settings or {}).get('opds', {}).get('hidden_entries', [])
    except Exception:
        hidden = []
    if not isinstance(hidden, list):
        return set()
    return {key for key in hidden if key in OPDS_ROOT_ENTRY_DEFS}


def get_opds_root_entries(user, allow_anonymous):
    hidden_entries = get_opds_hidden_entries_for_user(user)
    entries = []
    for key in get_opds_root_order_for_user(user):
        entry_def = OPDS_ROOT_ENTRY_DEFS.get(key)
        if not entry_def:
            continue
        if key in hidden_entries:
            continue
        if not entry_def['visible'](user, allow_anonymous):
            continue
        entries.append({
            'key': key,
            'title': _(entry_def['title']),
            'description': _(entry_def['description']),
            'url': url_for(entry_def['endpoint']),
        })
    return entries


def opds_only_selected_shelves(user=None):
    user = user or auth.current_user()
    return bool(getattr(user, 'opds_only_shelves_sync', 0))


def _get_opds_visible_shelf_clause(model, user=None):
    user = user or auth.current_user()
    if getattr(user, 'is_anonymous', False):
        return model.is_public == 1
    return or_(model.is_public == 1, model.user_id == user.id)


def get_opds_visible_shelves(user=None):
    user = user or auth.current_user()
    query = ub.session.query(ub.Shelf).filter(_get_opds_visible_shelf_clause(ub.Shelf, user))
    if opds_only_selected_shelves(user):
        query = query.join(
            ub.OpdsShelfExposure,
            and_(ub.OpdsShelfExposure.shelf_id == ub.Shelf.id, ub.OpdsShelfExposure.user_id == user.id),
        )
    return query


def get_opds_visible_magic_shelves(user=None):
    user = user or auth.current_user()
    query = ub.session.query(ub.MagicShelf).filter(_get_opds_visible_shelf_clause(ub.MagicShelf, user))
    if opds_only_selected_shelves(user):
        query = query.join(
            ub.OpdsMagicShelfExposure,
            and_(ub.OpdsMagicShelfExposure.shelf_id == ub.MagicShelf.id, ub.OpdsMagicShelfExposure.user_id == user.id),
        )
    return query


def is_opds_entity_exposed(entity, entity_type=None, user=None):
    user = user or auth.current_user()
    if not opds_only_selected_shelves(user):
        return True
    if entity_type == 'magic' or (entity_type is None and hasattr(entity, 'rules')):
        return ub.is_opds_magic_shelf_exposed_for_user(user.id, entity.id)
    if entity_type == 'shelf' or entity_type is None:
        return ub.is_opds_shelf_exposed_for_user(user.id, entity.id)
    return False


def authorize_opds_entity(entity, user=None, entity_type=None):
    user = user or auth.current_user()
    if entity is None:
        abort(404)
    if getattr(user, 'is_anonymous', False):
        if entity.is_public != 1:
            abort(404)
    elif entity.user_id != user.id and entity.is_public != 1:
        abort(403)
    if not is_opds_entity_exposed(entity, entity_type=entity_type, user=user):
        abort(404)
    return entity


def get_opds_restricted_common_filter(user=None):
    return calibre_db.common_filters(extra_filter=get_opds_book_filter(user))


def fill_opds_indexpage(*args, **kwargs):
    kwargs.setdefault('extra_filter', get_opds_book_filter())
    return calibre_db.fill_indexpage(*args, **kwargs)


def abort_unless_opds_book_exposed(book_id):
    if not is_opds_book_exposed(book_id):
        abort(404)


def build_opds_allowed_book_ids_query(user=None):
    user = user or auth.current_user()
    if not opds_only_selected_shelves(user):
        return None

    cache_key = '_opds_allowed_book_ids_query'
    cache_user_key = '_opds_allowed_book_ids_query_user_id'
    if getattr(g, cache_user_key, None) == user.id and hasattr(g, cache_key):
        return getattr(g, cache_key)

    allowed_book_ids_query = ub.session.query(ub.BookShelf.book_id).join(
        ub.Shelf,
        ub.BookShelf.shelf == ub.Shelf.id,
    ).join(
        ub.OpdsShelfExposure,
        and_(ub.OpdsShelfExposure.shelf_id == ub.Shelf.id, ub.OpdsShelfExposure.user_id == user.id),
    ).filter(
        _get_opds_visible_shelf_clause(ub.Shelf, user),
    )

    for shelf in get_opds_visible_magic_shelves(user).all():
        magic_query, __ = magic_shelf.build_book_query_for_magic_shelf(shelf.id, extra_filter=true())
        if magic_query is not None:
            allowed_book_ids_query = allowed_book_ids_query.union(magic_query.with_entities(db.Books.id))

    setattr(g, cache_key, allowed_book_ids_query)
    setattr(g, cache_user_key, user.id)
    return allowed_book_ids_query


def get_opds_book_filter(user=None):
    user = user or auth.current_user()
    if not opds_only_selected_shelves(user):
        return true()

    allowed_book_ids_query = build_opds_allowed_book_ids_query(user)
    if allowed_book_ids_query is None:
        return false()
    return db.Books.id.in_(allowed_book_ids_query)


def is_opds_book_exposed(book_id, user=None):
    user = user or auth.current_user()
    if not opds_only_selected_shelves(user):
        return True
    try:
        normalized_book_id = int(book_id)
    except (TypeError, ValueError):
        return False
    entry = calibre_db.session.query(db.Books.id).filter(
        db.Books.id == normalized_book_id,
        get_opds_restricted_common_filter(user),
    ).first()
    return entry is not None


@opds.before_request
def track_opds_access():
    """Track OPDS feed access for analytics"""
    try:
        from scripts.cwa_db import CWA_DB
        from .cw_login import current_user
        import json as json_lib
        
        # Only track if user is authenticated
        if current_user and hasattr(current_user, 'is_authenticated') and current_user.is_authenticated:
            cwa_db = CWA_DB()
            cwa_db.log_activity(
                user_id=int(current_user.id),
                user_name=current_user.name,
                event_type='OPDS_ACCESS',
                extra_data=json_lib.dumps({
                    'endpoint': request.path,
                    'method': request.method
                })
            )
    except Exception as e:
        log.debug(f"Failed to log OPDS access: {e}")


@opds.route("/opds/")
@opds.route("/opds")
@requires_basic_auth_if_no_ano
def feed_index():
    entries = get_opds_root_entries(auth.current_user(), g.allow_anonymous)
    return render_xml_template('index.xml', entries=entries)


@opds.route("/opds/osd")
@requires_basic_auth_if_no_ano
def feed_osd():
    # Issue #160 follow-up: reflect the resolved request locale instead of a
    # hardcoded en-EN, so OPDS search clients that present a localized UI from
    # OSD metadata pick up the language the user picked via ``?lang=`` or
    # Accept-Language. Falls back to the get_locale() default ('en') when
    # nothing else applies, matching pre-fix behavior.
    #
    # Build the atom search URL template here so the
    # ``?query={searchTerms}`` OpenSearch marker is merged onto whatever
    # query string ``url_defaults`` produced (notably ``?lang=xx``)
    # instead of clobbering it. The path-form template is rendered via
    # the ``opds_search_url_path`` context helper.
    atom_base = url_for('opds.feed_normal_search')
    atom_url = atom_base + ('&' if '?' in atom_base else '?') + 'query={searchTerms}'
    return render_xml_template(
        'osd.xml',
        lang=str(get_locale()),
        search_url_atom=atom_url,
    )


# @opds.route("/opds/search", defaults={'query': ""})
@opds.route("/opds/search/<path:query>")
@requires_basic_auth_if_no_ano
def feed_cc_search(query):
    # Handle strange query from Libera Reader with + instead of spaces.
    # Issue #160: now that ``?lang=`` is propagated via ``url_defaults``,
    # the raw URI for ``/opds/search/<query>`` ends up as
    # ``/opds/search/<query>?lang=xx`` and the previous .split() picked up
    # ``<query>?lang=xx`` as the search term, breaking every search.
    # Strip the query string before extracting the term.
    raw_uri = request.environ['RAW_URI'].split('/opds/search/', 1)[1]
    path_only = raw_uri.split('?', 1)[0]
    plus_query = unquote_plus(path_only).strip()
    return feed_search(plus_query)


@opds.route("/opds/search", methods=["GET"])
@requires_basic_auth_if_no_ano
def feed_normal_search():
    return feed_search(request.args.get("query", "").strip())


@opds.route("/opds/books")
@requires_basic_auth_if_no_ano
def feed_booksindex():
    return render_element_index(db.Books.sort, None, 'opds.feed_letter_books')


@opds.route("/opds/books/letter/<book_id>")
@requires_basic_auth_if_no_ano
def feed_letter_books(book_id):
    off = request.args.get("offset") or 0
    letter = true() if book_id == "00" else func.upper(db.Books.sort).startswith(book_id)
    entries, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1), 0,
                                                  db.Books,
                                                  letter,
                                                  [db.Books.sort],
                                                  True, config.config_read_column)

    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/new")
@requires_basic_auth_if_no_ano
def feed_new():
    if not auth.current_user().check_visibility(constants.SIDEBAR_RECENT):
        abort(404)
    off = request.args.get("offset") or 0
    entries, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1), 0,
                                                  db.Books, True, [db.Books.timestamp.desc()],
                                                  True, config.config_read_column)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/discover")
@requires_basic_auth_if_no_ano
def feed_discover():
    if not auth.current_user().check_visibility(constants.SIDEBAR_RANDOM):
        abort(404)
    query = calibre_db.generate_linked_query(config.config_read_column, db.Books)
    entries = query.filter(get_opds_restricted_common_filter()) \
        .order_by(func.random()).limit(config.config_books_per_page)
    pagination = Pagination(1, config.config_books_per_page, int(config.config_books_per_page))
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/rated")
@requires_basic_auth_if_no_ano
def feed_best_rated():
    if not auth.current_user().check_visibility(constants.SIDEBAR_BEST_RATED):
        abort(404)
    off = request.args.get("offset") or 0
    entries, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1), 0,
                                                  db.Books, db.Books.ratings.any(db.Ratings.rating > 9),
                                                  [db.Books.timestamp.desc()],
                                                  True, config.config_read_column)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/hot")
@requires_basic_auth_if_no_ano
def feed_hot():
    if not auth.current_user().check_visibility(constants.SIDEBAR_HOT):
        abort(404)
    off = request.args.get("offset") or 0
    all_books = ub.session.query(ub.Downloads, func.count(ub.Downloads.book_id)).order_by(
        func.count(ub.Downloads.book_id).desc()).group_by(ub.Downloads.book_id)
    hot_books = all_books.offset(off).limit(config.config_books_per_page)
    entries = list()
    for book in hot_books:
        query = calibre_db.generate_linked_query(config.config_read_column, db.Books)
        download_book = query.filter(get_opds_restricted_common_filter()).filter(
            book.Downloads.book_id == db.Books.id).first()
        if download_book:
            entries.append(download_book)
        else:
            ub.delete_download(book.Downloads.book_id)
    num_books = entries.__len__()
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1),
                            config.config_books_per_page, num_books)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/author")
@requires_basic_auth_if_no_ano
def feed_authorindex():
    if not auth.current_user().check_visibility(constants.SIDEBAR_AUTHOR):
        abort(404)
    return render_element_index(db.Authors.sort, db.books_authors_link, 'opds.feed_letter_author')


@opds.route("/opds/author/letter/<book_id>")
@requires_basic_auth_if_no_ano
def feed_letter_author(book_id):
    if not auth.current_user().check_visibility(constants.SIDEBAR_AUTHOR):
        abort(404)
    off = request.args.get("offset") or 0
    letter = true() if book_id == "00" else func.upper(db.Authors.sort).startswith(book_id)
    entries = calibre_db.session.query(db.Authors).join(db.books_authors_link).join(db.Books)\
        .filter(get_opds_restricted_common_filter()).filter(letter)\
        .group_by(text('books_authors_link.author'))\
        .order_by(db.Authors.sort)
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            entries.count())
    entries = entries.limit(config.config_books_per_page).offset(off).all()
    return render_xml_template('feed.xml', listelements=entries, folder='opds.feed_author', pagination=pagination)


@opds.route("/opds/author/<int:book_id>")
@requires_basic_auth_if_no_ano
def feed_author(book_id):
    return render_xml_dataset(db.Authors, book_id)


@opds.route("/opds/publisher")
@requires_basic_auth_if_no_ano
def feed_publisherindex():
    if not auth.current_user().check_visibility(constants.SIDEBAR_PUBLISHER):
        abort(404)
    off = request.args.get("offset") or 0
    entries = calibre_db.session.query(db.Publishers)\
        .join(db.books_publishers_link)\
        .join(db.Books).filter(get_opds_restricted_common_filter())\
        .group_by(text('books_publishers_link.publisher'))\
        .order_by(db.Publishers.sort)\
        .limit(config.config_books_per_page).offset(off)
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            len(calibre_db.session.query(db.Publishers).all()))
    return render_xml_template('feed.xml', listelements=entries, folder='opds.feed_publisher', pagination=pagination)


@opds.route("/opds/publisher/<int:book_id>")
@requires_basic_auth_if_no_ano
def feed_publisher(book_id):
    return render_xml_dataset(db.Publishers, book_id)


@opds.route("/opds/category")
@requires_basic_auth_if_no_ano
def feed_categoryindex():
    if not auth.current_user().check_visibility(constants.SIDEBAR_CATEGORY):
        abort(404)
    return render_element_index(db.Tags.name, db.books_tags_link, 'opds.feed_letter_category')


@opds.route("/opds/category/letter/<book_id>")
@requires_basic_auth_if_no_ano
def feed_letter_category(book_id):
    if not auth.current_user().check_visibility(constants.SIDEBAR_CATEGORY):
        abort(404)
    off = request.args.get("offset") or 0
    letter = true() if book_id == "00" else func.upper(db.Tags.name).startswith(book_id)
    entries = calibre_db.session.query(db.Tags)\
        .join(db.books_tags_link)\
        .join(db.Books)\
        .filter(get_opds_restricted_common_filter()).filter(letter)\
        .group_by(text('books_tags_link.tag'))\
        .order_by(db.Tags.name)
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            entries.count())
    entries = entries.offset(off).limit(config.config_books_per_page).all()
    return render_xml_template('feed.xml', listelements=entries, folder='opds.feed_category', pagination=pagination)


@opds.route("/opds/category/<int:book_id>")
@requires_basic_auth_if_no_ano
def feed_category(book_id):
    return render_xml_dataset(db.Tags, book_id)


@opds.route("/opds/series")
@requires_basic_auth_if_no_ano
def feed_seriesindex():
    if not auth.current_user().check_visibility(constants.SIDEBAR_SERIES):
        abort(404)
    return render_element_index(db.Series.sort, db.books_series_link, 'opds.feed_letter_series')


@opds.route("/opds/series/letter/<book_id>")
@requires_basic_auth_if_no_ano
def feed_letter_series(book_id):
    if not auth.current_user().check_visibility(constants.SIDEBAR_SERIES):
        abort(404)
    off = request.args.get("offset") or 0
    letter = true() if book_id == "00" else func.upper(db.Series.sort).startswith(book_id)
    entries = calibre_db.session.query(db.Series)\
        .join(db.books_series_link)\
        .join(db.Books)\
        .filter(get_opds_restricted_common_filter()).filter(letter)\
        .group_by(text('books_series_link.series'))\
        .order_by(db.Series.sort)
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            entries.count())
    entries = entries.offset(off).limit(config.config_books_per_page).all()
    return render_xml_template('feed.xml', listelements=entries, folder='opds.feed_series', pagination=pagination)


@opds.route("/opds/series/<int:book_id>")
@requires_basic_auth_if_no_ano
def feed_series(book_id):
    off = request.args.get("offset") or 0
    entries, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1), 0,
                                                  db.Books,
                                                  db.Books.series.any(db.Series.id == book_id),
                                                  [db.Books.series_index],
                                                  True, config.config_read_column)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/ratings")
@requires_basic_auth_if_no_ano
def feed_ratingindex():
    if not auth.current_user().check_visibility(constants.SIDEBAR_RATING):
        abort(404)
    off = request.args.get("offset") or 0
    entries = calibre_db.session.query(db.Ratings, func.count('books_ratings_link.book').label('count'),
                                       (db.Ratings.rating / 2).label('name')) \
        .join(db.books_ratings_link)\
        .join(db.Books)\
        .filter(get_opds_restricted_common_filter()) \
        .group_by(text('books_ratings_link.rating'))\
        .order_by(db.Ratings.rating).all()

    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            len(entries))
    element = list()
    for entry in entries:
        element.append(FeedObject(entry[0].id, _("{} Stars").format(_format_opds_rating(entry.name))))
    return render_xml_template('feed.xml', listelements=element, folder='opds.feed_ratings', pagination=pagination)


@opds.route("/opds/ratings/<book_id>")
@requires_basic_auth_if_no_ano
def feed_ratings(book_id):
    return render_xml_dataset(db.Ratings, book_id)


@opds.route("/opds/formats")
@requires_basic_auth_if_no_ano
def feed_formatindex():
    if not auth.current_user().check_visibility(constants.SIDEBAR_FORMAT):
        abort(404)
    off = request.args.get("offset") or 0
    entries = calibre_db.session.query(db.Data).join(db.Books)\
        .filter(get_opds_restricted_common_filter()) \
        .group_by(db.Data.format)\
        .order_by(db.Data.format).all()
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            len(entries))
    element = list()
    for entry in entries:
        element.append(FeedObject(entry.format, entry.format))
    return render_xml_template('feed.xml', listelements=element, folder='opds.feed_format', pagination=pagination)


@opds.route("/opds/formats/<book_id>")
@requires_basic_auth_if_no_ano
def feed_format(book_id):
    off = request.args.get("offset") or 0
    entries, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1), 0,
                                                  db.Books,
                                                  db.Books.data.any(db.Data.format == book_id.upper()),
                                                  [db.Books.timestamp.desc()],
                                                  True, config.config_read_column)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/language")
@opds.route("/opds/language/")
@requires_basic_auth_if_no_ano
def feed_languagesindex():
    if not auth.current_user().check_visibility(constants.SIDEBAR_LANGUAGE):
        abort(404)
    off = request.args.get("offset") or 0
    if auth.current_user().filter_language() == "all":
        languages = calibre_db.session.query(db.Languages).join(db.books_languages_link).join(db.Books).filter(
            get_opds_restricted_common_filter()
        ).group_by(text('books_languages_link.lang_code')).all()
        for language in languages:
            language.name = isoLanguages.get_language_name(get_locale(), language.lang_code)
    else:
        languages = calibre_db.session.query(db.Languages).join(db.books_languages_link).join(db.Books).filter(
            db.Languages.lang_code == auth.current_user().filter_language()
        ).filter(get_opds_restricted_common_filter()).group_by(db.Languages.id).all()
        if languages:
            languages[0].name = isoLanguages.get_language_name(get_locale(), languages[0].lang_code)
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            len(languages))
    return render_xml_template('feed.xml', listelements=languages, folder='opds.feed_languages', pagination=pagination)


@opds.route("/opds/language/<int:book_id>")
@requires_basic_auth_if_no_ano
def feed_languages(book_id):
    off = request.args.get("offset") or 0
    entries, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1), 0,
                                                  db.Books,
                                                  db.Books.languages.any(db.Languages.id == book_id),
                                                  [db.Books.timestamp.desc()],
                                                  True, config.config_read_column)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/shelfindex")
@requires_basic_auth_if_no_ano
def feed_shelfindex():
    if not (auth.current_user().is_authenticated or g.allow_anonymous):
        abort(404)
    off = request.args.get("offset") or 0
    shelf = get_opds_visible_shelves().order_by(ub.Shelf.name).all()
    number = len(shelf)
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            number)
    return render_xml_template('feed.xml', listelements=shelf, folder='opds.feed_shelf', pagination=pagination)


@opds.route("/opds/magicshelfindex")
@requires_basic_auth_if_no_ano
def feed_magic_shelfindex():
    if not (auth.current_user().is_authenticated or g.allow_anonymous):
        abort(404)
    off = request.args.get("offset") or 0

    magic_shelves = get_opds_visible_magic_shelves().order_by(ub.MagicShelf.name).all()

    class OpdsMagicShelfEntry:
        def __init__(self, magic):
            self.id = magic.id
            self.name = magic.name
            self.is_public = magic.is_public
            self.icon = magic.icon
            self.is_magic_shelf = True
            self.opds_url = url_for('opds.feed_magic_shelf', shelf_id=magic.id)

    listelements = [OpdsMagicShelfEntry(magic) for magic in magic_shelves]
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1),
                            config.config_books_per_page,
                            len(listelements))
    return render_xml_template('feed.xml', listelements=listelements, folder='opds.feed_magic_shelf', pagination=pagination)


@opds.route("/opds/shelf/<int:book_id>")
@requires_basic_auth_if_no_ano
def feed_shelf(book_id):
    if not (auth.current_user().is_authenticated or g.allow_anonymous):
        abort(404)
    off = request.args.get("offset") or 0
    shelf = ub.session.query(ub.Shelf).filter(ub.Shelf.id == book_id).first()
    if not shelf:
        abort(404)
    result = list()
    pagination = list()
    # user is allowed to access shelf
    authorize_opds_entity(shelf, entity_type='shelf')
    result, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1),
                                                 config.config_books_per_page,
                                                 db.Books,
                                                 ub.BookShelf.shelf == shelf.id,
                                                 [ub.BookShelf.order.asc()],
                                                 True, config.config_read_column,
                                                 ub.BookShelf, ub.BookShelf.book_id == db.Books.id)
    # delete shelf entries where book is not existent anymore, can happen if book is deleted outside calibre-web
    wrong_entries = calibre_db.session.query(ub.BookShelf) \
        .join(db.Books, ub.BookShelf.book_id == db.Books.id, isouter=True) \
        .filter(db.Books.id == None).all()
    for entry in wrong_entries:
        log.info('Not existing book {} in {} deleted'.format(entry.book_id, shelf))
        try:
            ub.session.query(ub.BookShelf).filter(ub.BookShelf.book_id == entry.book_id).delete()
            ub.session.commit()
        except (OperationalError, InvalidRequestError) as e:
            ub.session.rollback()
            log.error_or_exception("Settings Database error: {}".format(e))
    return render_xml_template('feed.xml', entries=result, pagination=pagination)


@opds.route("/opds/magicshelf/<int:shelf_id>")
@requires_basic_auth_if_no_ano
def feed_magic_shelf(shelf_id):
    if not (auth.current_user().is_authenticated or g.allow_anonymous):
        abort(404)
    off = request.args.get("offset") or 0

    shelf = ub.session.query(ub.MagicShelf).get(shelf_id)
    if not shelf:
        abort(404)

    authorize_opds_entity(shelf, entity_type='magic')

    per_page = int(config.config_books_per_page) if config.config_books_per_page else 20
    page = int(off) // per_page + 1
    sort_order = [db.Books.timestamp.desc()]
    query, __ = magic_shelf.build_book_query_for_magic_shelf(
        shelf_id,
        sort_order=sort_order,
        extra_filter=get_opds_book_filter(),
    )
    if query is None:
        books = []
        total_count = 0
    else:
        total_count = query.order_by(None).count()
        books = query.limit(per_page).offset((page - 1) * per_page).all()

    class Entry:
        def __init__(self, book):
            self.Books = book

    entries = [Entry(book) for book in books]
    pagination = Pagination(page, per_page, total_count)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


@opds.route("/opds/download/<book_id>/<book_format>/")
@requires_basic_auth_if_no_ano
def opds_download_link(book_id, book_format):
    if not auth.current_user().role_download():
        return abort(401)
    abort_unless_opds_book_exposed(book_id)
    client = "kobo" if "Kobo" in request.headers.get('User-Agent') else ""
    return get_download_link(book_id, book_format.lower(), client)


@opds.route("/ajax/book/<string:uuid>/<library>")
@opds.route("/ajax/book/<string:uuid>", defaults={'library': ""})
@requires_basic_auth_if_no_ano
def get_metadata_calibre_companion(uuid, library):
    entry = calibre_db.session.query(db.Books).filter(db.Books.uuid.like("%" + uuid + "%")).first()
    if entry is not None and is_opds_book_exposed(entry.id):
        js = render_template('json.txt', entry=entry)
        response = make_response(js)
        response.headers["Content-Type"] = "application/json; charset=utf-8"
        return response
    else:
        return ""


@opds.route("/opds/stats")
@requires_basic_auth_if_no_ano
def get_database_stats():
    stat = dict()
    stat['books'] = calibre_db.session.query(db.Books).filter(
        get_opds_restricted_common_filter()
    ).count()
    stat['authors'] = calibre_db.session.query(db.Authors).join(db.books_authors_link).join(db.Books).filter(
        get_opds_restricted_common_filter()
    ).group_by(db.Authors.id).count()
    stat['categories'] = calibre_db.session.query(db.Tags).join(db.books_tags_link).join(db.Books).filter(
        get_opds_restricted_common_filter()
    ).group_by(db.Tags.id).count()
    stat['series'] = calibre_db.session.query(db.Series).join(db.books_series_link).join(db.Books).filter(
        get_opds_restricted_common_filter()
    ).group_by(db.Series.id).count()
    return Response(json.dumps(stat), mimetype="application/json")


@opds.route("/opds/thumb_240_240/<book_id>")
@opds.route("/opds/cover_240_240/<book_id>")
@opds.route("/opds/cover_90_90/<book_id>")
@opds.route("/opds/cover/<book_id>")
@requires_basic_auth_if_no_ano
def feed_get_cover(book_id):
    abort_unless_opds_book_exposed(book_id)
    return get_book_cover(book_id)


@opds.route("/opds/readbooks")
@requires_basic_auth_if_no_ano
def feed_read_books():
    if not (auth.current_user().check_visibility(constants.SIDEBAR_READ_AND_UNREAD) and not auth.current_user().is_anonymous):
        return abort(403)
    off = request.args.get("offset") or 0
    result, pagination = render_read_books(int(off) / (int(config.config_books_per_page)) + 1,
                                           True,
                                           True,
                                           extra_filter=get_opds_book_filter())
    return render_xml_template('feed.xml', entries=result, pagination=pagination)


@opds.route("/opds/unreadbooks")
@requires_basic_auth_if_no_ano
def feed_unread_books():
    if not (auth.current_user().check_visibility(constants.SIDEBAR_READ_AND_UNREAD) and not auth.current_user().is_anonymous):
        return abort(403)
    off = request.args.get("offset") or 0
    result, pagination = render_read_books(int(off) / (int(config.config_books_per_page)) + 1,
                                           False,
                                           True,
                                           extra_filter=get_opds_book_filter())
    return render_xml_template('feed.xml', entries=result, pagination=pagination)


class FeedObject:
    def __init__(self, rating_id, rating_name):
        self.rating_id = rating_id
        self.rating_name = rating_name

    @property
    def id(self):
        return self.rating_id

    @property
    def name(self):
        return self.rating_name


def feed_search(term):
    if term:
        # Keep OPDS search filtering local to opds.py so this feature does not widen
        # the shared CalibreDB search API surface just for OPDS-only restrictions.
        entries = calibre_db.search_query(term, config=config).filter(get_opds_book_filter()).order_by(db.Books.sort).all()
        entries_count = len(entries) if len(entries) > 0 else 1
        pagination = Pagination(1, entries_count, entries_count)
        return render_xml_template('feed.xml', searchterm=term, entries=entries, pagination=pagination)
    else:
        return render_xml_template('feed.xml', searchterm="")



# Fork issue #183 / @droM4X: ``/opds/<anything-not-a-real-route>`` used
# to fall through to the stock-Calibre-Web ``@web.route('/<data>/<sort_param>/')``
# pair, which renders the full HTML books grid — OPDS clients hitting a
# forged URL got an HTML web page instead of a proper 404. The
# blueprint-scoped catch-all below grabs any unmatched ``/opds/*`` path
# and returns 404 with an Atom-shaped body, so the web catch-all never
# sees it. The ``<path:_unknown>`` converter matches multi-segment
# forged paths (``/opds/a/b/c``) as well — bare ``<_unknown>`` would
# miss those. Flask's URL map prefers literal-prefix routes over
# converter routes, so every defined OPDS endpoint above still wins
# this catch-all for its specific path.
@opds.route("/opds/<path:_unknown>")
def _opds_feed_not_found(_unknown):
    body = (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<feed xmlns="http://www.w3.org/2005/Atom">\n'
        '  <id>opds-not-found</id>\n'
        '  <title>Not Found</title>\n'
        '</feed>\n'
    )
    response = make_response(body, 404)
    response.headers["Content-Type"] = "application/atom+xml; charset=utf-8"
    return response


# Fork issue #224 / @droM4X: errors raised from inside OPDS routes
# (``abort(404)`` for unknown book ids, ``abort(403)`` for denied tags,
# unhandled exceptions, etc.) used to surface as stock Flask HTML error
# pages — readers like Readest / KOReader can't parse HTML and showed
# the user "broken feed" with no useful info. The blueprint-level
# errorhandlers below catch each HTTP error code and return a small
# Atom-shaped body with the correct ``application/atom+xml`` content-
# type and the original status code preserved.
#
# 401 also sets ``WWW-Authenticate: Basic realm="OPDS"`` so HTTP-Basic
# readers prompt the user for credentials instead of silently failing.
# (Flask-HTTPAuth's own ``auth_error_callback`` short-circuits for the
# authenticate-required decorator path — that response already carries
# the right header. This handler covers any explicit ``abort(401)`` from
# inside an OPDS route, e.g. reverse-proxy header rejection.)
def _opds_error_body(title, error_id):
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<feed xmlns="http://www.w3.org/2005/Atom">\n'
        f'  <id>{error_id}</id>\n'
        f'  <title>{title}</title>\n'
        '</feed>\n'
    )


@opds.errorhandler(401)
def _opds_unauthorized(_error):
    response = make_response(_opds_error_body("Unauthorized", "opds-unauthorized"), 401)
    response.headers["Content-Type"] = "application/atom+xml; charset=utf-8"
    response.headers["WWW-Authenticate"] = 'Basic realm="OPDS"'
    return response


@opds.errorhandler(403)
def _opds_forbidden(_error):
    response = make_response(_opds_error_body("Forbidden", "opds-forbidden"), 403)
    response.headers["Content-Type"] = "application/atom+xml; charset=utf-8"
    return response


@opds.errorhandler(404)
def _opds_not_found(_error):
    response = make_response(_opds_error_body("Not Found", "opds-not-found"), 404)
    response.headers["Content-Type"] = "application/atom+xml; charset=utf-8"
    return response


@opds.errorhandler(500)
def _opds_internal_error(_error):
    response = make_response(_opds_error_body("Internal Server Error", "opds-internal-error"), 500)
    response.headers["Content-Type"] = "application/atom+xml; charset=utf-8"
    return response


def render_xml_template(*args, **kwargs):
    # ToDo: return time in current timezone similar to %z
    currtime = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S+00:00")
    xml = render_template(current_time=currtime, instance=config.config_calibre_web_title, constants=constants.sidebar_settings, *args, **kwargs)
    response = make_response(xml)
    response.headers["Content-Type"] = "application/atom+xml; charset=utf-8"
    return response


def render_xml_dataset(data_table, book_id):
    off = request.args.get("offset") or 0
    entries, __, pagination = fill_opds_indexpage((int(off) / (int(config.config_books_per_page)) + 1), 0,
                                                  db.Books,
                                                  getattr(db.Books, data_table.__tablename__).any(data_table.id == book_id),
                                                  [db.Books.timestamp.desc()],
                                                  True, config.config_read_column)
    return render_xml_template('feed.xml', entries=entries, pagination=pagination)


def render_element_index(database_column, linked_table, folder):
    shift = 0
    off = int(request.args.get("offset") or 0)
    entries = calibre_db.session.query(func.upper(func.substr(database_column, 1, 1)).label('id'), None, None)
    # query = calibre_db.generate_linked_query(config.config_read_column, db.Books)
    if linked_table is not None:
        entries = entries.join(linked_table).join(db.Books)
    entries = entries.filter(get_opds_restricted_common_filter()) \
        .group_by(func.upper(func.substr(database_column, 1, 1))).all()
    elements = []
    if off == 0 and entries:
        elements.append({'id': "00", 'name': _("All")})
        shift = 1
    for entry in entries[
                 off + shift - 1:
                 int(off + int(config.config_books_per_page) - shift)]:
        elements.append({'id': entry.id, 'name': entry.id})
    pagination = Pagination((int(off) / (int(config.config_books_per_page)) + 1), config.config_books_per_page,
                            len(entries) + 1)
    return render_xml_template('feed.xml',
                               letterelements=elements,
                               folder=folder,
                               pagination=pagination)
