# Calibre-Web Automated – fork of Calibre-Web
# Copyright (C) 2018-2026 Calibre-Web contributors
# Copyright (C) 2024-2026 Calibre-Web Automated contributors
# SPDX-License-Identifier: GPL-3.0-or-later

"""Structural convention check for wrapped strings in shipped .po files.

Background (fork PR #429, closed unmerged): an i18n edit misread the PO
multi-line form

    msgstr ""
    "Base de données de Calibre indisponible. Veuillez reconfigurer le chemin de "
    "la bibliothèque."

as an *empty* msgstr — `msgstr ""` followed by continuation strings is a
complete translation (gettext concatenates adjacent strings). The edit
replaced only the first line and left the continuation lines in place, so
the compiled msgstr became the message doubled. ``msgfmt`` accepts that
shape, so ``test_translations_compile.py`` stayed green and CI could not
catch it.

Every .po file we ship is generated by pybabel/Weblate, which always emit
wrapped entries with an *empty* first line (verified repo-wide: 28 files,
zero exceptions). This test pins that convention: any msgid/msgstr whose
first line is non-empty AND is followed by continuation string lines is a
hand-edit gone wrong, almost certainly a half-replaced wrapped entry.
"""

import glob
import os
import re

import pytest


REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TRANSLATIONS_DIR = os.path.join(REPO_ROOT, "cps", "translations")

# msgid / msgid_plural / msgstr / msgstr[N] with non-empty quoted content.
_KEYWORD_NONEMPTY = re.compile(r'^(msgid|msgid_plural|msgstr(?:\[\d+\])?) "(.+)"\s*$')
# A bare continuation string line.
_CONTINUATION = re.compile(r'^"')


def find_wrapped_nonempty_first_lines(lines):
    """Return [(line_no, line)] where a non-empty msgid/msgstr first line
    is directly followed by a continuation string line.

    In well-formed pybabel/Weblate output, wrapped entries always start
    with ``msgid ""`` / ``msgstr ""``. A non-empty first line with
    continuations concatenates into one string and usually means a wrapped
    entry was half-replaced by hand (the PR #429 corruption shape).
    """
    violations = []
    for i, line in enumerate(lines):
        if _KEYWORD_NONEMPTY.match(line) and i + 1 < len(lines) and _CONTINUATION.match(lines[i + 1]):
            violations.append((i + 1, line.rstrip()))
    return violations


def _discover_po_files():
    pattern = os.path.join(TRANSLATIONS_DIR, "*", "LC_MESSAGES", "messages.po")
    return sorted(glob.glob(pattern))


PO_FILES = _discover_po_files()


@pytest.mark.unit
def test_detector_flags_half_replaced_wrapped_msgstr():
    """The detector must catch the exact corruption shape from PR #429."""
    corrupted = [
        'msgid "Calibre database unavailable. Please reconfigure the library path."\n',
        'msgstr "Base de données Calibre indisponible. Veuillez reconfigurer le chemin de la bibliothèque."\n',
        '"Base de données de Calibre indisponible. Veuillez reconfigurer le chemin de "\n',
        '"la bibliothèque."\n',
    ]
    violations = find_wrapped_nonempty_first_lines(corrupted)
    assert len(violations) == 1
    assert violations[0][0] == 2


@pytest.mark.unit
def test_detector_accepts_wellformed_shapes():
    """Empty-first-line wrapping, single-line entries, and adjacent entries
    must not be flagged."""
    wellformed = [
        'msgid "Calibre database unavailable. Please reconfigure the library path."\n',
        'msgstr ""\n',
        '"Base de données de Calibre indisponible. Veuillez reconfigurer le chemin de "\n',
        '"la bibliothèque."\n',
        '\n',
        'msgid "Statistics"\n',
        'msgstr "Statistiques"\n',
        '\n',
        'msgid ""\n',
        '"A long source string that pybabel wrapped across "\n',
        '"two lines."\n',
        'msgstr "Une seule ligne."\n',
    ]
    assert find_wrapped_nonempty_first_lines(wellformed) == []


@pytest.mark.unit
@pytest.mark.parametrize("po_path", PO_FILES, ids=lambda p: p.split(os.sep)[-3])
def test_no_half_replaced_wrapped_strings(po_path):
    with open(po_path, encoding="utf-8") as f:
        lines = f.readlines()
    violations = find_wrapped_nonempty_first_lines(lines)
    if violations:
        locale = po_path.split(os.sep)[-3]
        detail = "\n".join(f"  line {n}: {l}" for n, l in violations)
        pytest.fail(
            f"Locale {locale!r}: wrapped msgid/msgstr with a non-empty first line —\n"
            f"{detail}\n"
            f"gettext concatenates adjacent strings, so this almost certainly\n"
            f"duplicates part of the message. If the entry was meant to be\n"
            f"replaced, remove its continuation lines too; pybabel/Weblate\n"
            f"always emit wrapped entries with an empty first line.\n"
        )
