#!/bin/bash

# https://github.com/janeczku/calibre-web/wiki/Automatically-import-new-books-(Linux)

# This script is used to automatically import downloaded ebooks into a Calibre database.
# Reference: https://manual.calibre-ebook.com/generated/en/calibredb.html#add
echo "========== STARTING CWA-INGEST SERVICE =========="

REPO_ROOT="/app/calibre-web-automated"
if [[ -f "/etc/cwa-repo-root" ]]; then
  REPO_ROOT="$(cat /etc/cwa-repo-root)"
fi
DIRS_JSON="${REPO_ROOT}/dirs.json"

WATCH_FOLDER=$(grep -o '"ingest_folder": "[^"]*' "$DIRS_JSON" | grep -o '[^"]*$')
echo "[cwa-ingest-service] Watching folder: $WATCH_FOLDER"

# Monitor the folder for new files
s6-setuidgid abc inotifywait -m -r --format="%e %w%f" -e close_write -e moved_to "$WATCH_FOLDER" |
while read -r events filepath ; do
        # if [[ $(grep "$filepath" ingest-log-test.txt | egrep -o '[0-9]{10}') ]]; then
        #         CURRENT_TIME=$(date +'%s')
        #         TIME_OF_MATCH=$(grep "$filepath" ingest-log-test.txt | egrep -o '[0-9]{10}')
        #         TODO NEED TO GET DIFFERENCE BETWEEN THE 2 TIMES AND IF LESS THAN 60 SECONDS, IGNORE
        echo "[cwa-ingest-service] New files detected - $filepath - Starting Ingest Processor..."
        python3 -m cps.ingest_processor "$filepath" # &
        # echo "'${filepath}' - $(date +'%s')" >> /config/.ingest_dupe_list
        # INGEST_PROCESSOR_PID=$!
        # Wait for the ingest processor to finish
        # wait $INGEST_PROCESSOR_PID
        # if ! [[ $(ls -A "$WATCH_FOLDER") ]]; then
        #         FILES="${WATCH_FOLDER}/*"
        #         for f in $FILES
        #         do
        #                 python3 /app/calibre-web-automated/ingest_processor.py "$f" &
        #                 INGEST_PROCESSOR_PID=$!
        #                 # Wait for the ingest processor to finish
        #                 wait $INGEST_PROCESSOR_PID
        #         done
        # fi
done

