#!/bin/bash

echo "[cwa-set-binary-paths] Setting binary paths in '/config/app.db' to the correct ones..."

sqlite3 /config/app.db <<EOS
    update settings set config_kepubifypath='/usr/bin/kepubify', config_converterpath='/usr/bin/ebook-convert', config_binariesdir='/usr/bin';
EOS

if [[ $? == 0 ]]
then
    echo "[cwa-set-binary-paths] Successfully set binary paths in '/config/app.db'!"
elif [[ $? > 0 ]]
then
    echo "[cwa-set-binary-paths] Service could not successfully set binary paths for '/config/app.db' (see errors above)."
fi

echo "[cwa-set-binary-paths] Service exiting now..."